---
# file: roles/fabric-ca/tasks/main.yml
#
# file: make sure directories exists
- name: fabric-ca | make sure direcoties needed by fabric-ca exists
  file:
    path: "/hfc-data/{{ inventory_hostname|lower|replace('-','_') }}/{{ item }}/"
    state: directory
    owner: root
    group: root
    mode: 0644
  with_items:
    - restore
    - configtx

# copy: copy crypto for fabric-ca
- name: fabric-ca | copy crypto for fabric-ca
  copy:
    src: "{{ ca_org_id | lower }}/ca/"
    dest: /hfc-data/{{ inventory_hostname|lower|replace('-','_') }}/configtx/
    owner: root
    group: root
    mode: 0644

# template: copy env_file for fabric-ca
- name: fabric-ca | copy env_file for fabric-ca
  template:
    src: env_file.j2
    dest: /hfc-data/{{ inventory_hostname|lower|replace('-','_') }}/restore/env_file

# docker_container: start containers of fabric-ca
- name: fabric-ca | launch fabric-ca
  docker_container:
    name: "{{ inventory_hostname|lower|replace('-','_') }}"
    hostname: "{{ inventory_hostname|lower|replace('-','_') }}"
    image: "{{ hfc_images.ca.tags.0 }}"
    env_file: /hfc-data/{{ inventory_hostname|lower|replace('-','_') }}/restore/env_file
    volumes:
      - /hfc-data/{{ inventory_hostname|lower|replace('-','_') }}/configtx/:/etc/hyperledger/configtx/
    ports:
      - "0.0.0.0:{{ ca_expose_port }}:{{ ca_listen_port }}"
    command:
      fabric-ca-server start -b admin:adminpw
    dns_servers:
      - "{{ hostvars[groups['dns-server'].0].ansible_host }}"
      - "{{ hostvars[groups['dns-server'].1].ansible_host }}"
    dns_search_domains:
      - "{{ dnsmasq_domain }}"
    labels:
      com.jcloud.group: "fabric"
      com.jcloud.nodetype: "ca"
    restart_policy: always
    restart: yes
    state: started

# template: generate restore script for fabric-ca
- name: fabric-ca | generate restore script for fabric-ca
  template:
    src: run_new.sh.j2
    dest: /hfc-data/{{ inventory_hostname|lower|replace('-','_') }}/restore/run-{{ inventory_hostname|lower|replace('-','_') }}.sh
    mode: 0755

# cron: setup cron jobs for backup of fabric-ca
#       ONLY satinize the file name for /etc/cron.d, cause '.' is not supported!!
- name: fabric-ca | setup cron jobs for backup of fabric-ca
  cron:
    name: backup /hfc-data/{{ inventory_hostname|lower|replace('-','_') }}
    minute: "{{ ( inventory_hostname|lower|replace('-','_') | hash | list | map('int',0,128) | sum ) % 60 }}"
    hour: "{{ (( inventory_hostname|lower|replace('-','_') | hash | list | map('int',0,128) | sum ) % 3) + 1 }}"
    user: root
    job: "/usr/local/bin/fabric-backup.sh {{ inventory_hostname|lower|replace('-','_') }}"
    cron_file: "{{ inventory_hostname|lower|replace('-','_')|replace('.','_') }}-backup"
