---
# file: roles/mon-registry.hfc.test.io:5000/grafana/defaults/main.yml
grafana_image: registry.hfc.test.io:5000/grafana/grafana:latest

#grafana_listen_port: 3000
grafana_expose_port: 9095
grafana_admin_user: admin
grafana_admin_password: P@ssw0rd
grafana_allow_sign_up: false
